"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, BookOpen, Building2, FileImage, FileText, GitBranch, Lightbulb, Menu, Presentation, Search, Send, Tag, Users, Video, X } from "lucide-react";
import { STUDENT_PROJECTS } from "@/mock/student-projects";

const journey = [["01", "UPLOAD", "Add your project context", FileText], ["02", "UNDERSTAND", "Read the full opportunity", Search], ["03", "RESEARCH", "Validate the whitespace", BarChart3], ["04", "BRAND", "Shape your identity", Tag], ["05", "BUSINESS MODEL", "Build the route to value", BookOpen], ["06", "PITCH", "Tell the story clearly", Presentation], ["07", "MENTOR", "Find the right guidance", Users], ["08", "FUND", "Unlock the next milestone", Building2], ["09", "LAUNCH", "Take it to market", Send], ["10", "IMPACT", "Measure what changes", Lightbulb]] as const;
const agents = [["Research Agent", "Finds research, patents and existing solutions", Search, "blue"], ["Innovation Agent", "Evaluates uniqueness and feasibility", Lightbulb, "purple"], ["Market Agent", "Analyses market size, competitors and trends", BarChart3, "violet"], ["Branding Agent", "Generates name, tagline, logo and identity", Tag, "rose"], ["Business Agent", "Creates business model and revenue plan", FileText, "lavender"], ["Pitch Agent", "Builds investor-ready pitch deck", Presentation, "sky"], ["Mentor Agent", "Recommends mentors, investors and programs", Users, "indigo"]] as const;
const formats = [[FileText, "PDF"], [Presentation, "PPT"], [FileImage, "Images"], [Video, "Video"], [GitBranch, "GitHub"], [FileText, "Research Papers"]] as const;
const outputs = [["Innovation report", "A clear read on novelty, feasibility and next steps", Lightbulb], ["Competitor analysis", "Market context your team can actually act on", BarChart3], ["Patent + research analysis", "Evidence, whitespace and relevant prior art", Search], ["Business model", "A practical path from idea to revenue", BookOpen], ["Startup branding", "Name, story, identity and positioning", Tag], ["Pitch deck", "A sharper case for mentors and investors", Presentation], ["Go-to-market strategy", "Channels, audiences and launch sequence", Send], ["Mentor recommendations", "The right people for the next milestone", Users]] as const;
const demoProjects = [["Make-a-thon", "A hands-on platform for turning problems into prototypes", "Ideation + building", "Student teams in action", "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=85"], ["Startup Forum", "Conversations that connect students with the startup ecosystem", "Mentors + investors", "Ideas meet experience", "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85"], ["Brand Challenge", "A practical challenge in positioning, storytelling, and business", "Brand + strategy", "Skills built through practice", "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=85"]] as const;
const pathways = [["RESEARCH / PROJECT OWNERS", "Start with a question, a prototype, or a research insight and move it toward a useful venture.", "Research to venture", Lightbulb, "research-product-owners", "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=900&q=85"], ["FACULTY COORDINATORS", "Coordinate projects, programmes, reviews, and the people helping ideas progress.", "Coordinate a programme", Building2, "faculty-coordinators", "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=85"], ["INDUSTRY PARTNERS", "Bring practical context, collaboration, and pathways into the world outside campus.", "Partner with the ecosystem", Users, "industry-guides", "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85"], ["INVESTORS", "Discover researched opportunities and support the next generation of ventures.", "Explore opportunities", BarChart3, "industry-investors", "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=85"], ["MENTORS", "Share hard-earned perspective at the moment a student team needs it most.", "Become a mentor", Send, "industry-guides", "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=900&q=85"]] as const;
const images = { hero: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=2200&q=85", lab: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1800&q=85", office: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=85", campus: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1800&q=85" };
const projectFilters = ["ALL", "AI", "AIML", "IOT", "SUSTAINABILITY", "HEALTHCARE", "FINTECH"] as const;
const fundingJourney = [["PROJECT", Lightbulb], ["INCUBATION", Building2], ["VALIDATION", Search], ["INVESTOR CONNECT", Users], ["FUNDING", BarChart3], ["GROWTH", ArrowUpRight]] as const;

const projectDomain = (domain: string) => {
  if (domain.includes("Health")) return "HEALTHCARE";
  if (domain.includes("Energy") || domain.includes("Smart Cities")) return "SUSTAINABILITY";
  if (domain.includes("Agri")) return "AI";
  if (domain.includes("Mobility")) return "IOT";
  return "ALL";
};

const projectStage = (maturity: string) => maturity === "MVP" ? "IN PROGRESS" : maturity === "PROTOTYPE" ? "PROTOTYPE" : "IDEATION";
const successStories = [["DEMO STORY", "Verified success stories will appear here once outcomes are approved.", "PROJECT DATA PENDING", "STARTUP OUTCOME PENDING"], ["COMING SOON", "A real founder story will connect project work to measurable impact.", "FOUNDER DATA PENDING", "ACHIEVEMENT DATA PENDING"]] as const;
const impactMetrics = ["PROJECTS", "STARTUPS", "MENTORS", "EVENTS", "FUNDING", "PARTNERS", "STUDENTS"] as const;
const eventTypes = ["HACKATHONS", "WORKSHOPS", "MENTORSHIP", "COMPETITIONS", "TALKS", "DEMO DAYS", "INVESTOR MEETS"] as const;
const mentorFilters = ["ALL", "TECHNOLOGY", "BUSINESS", "MARKETING", "FINANCE", "LEGAL", "PRODUCT", "FUNDING"] as const;

export default function RootPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeProject, setActiveProject] = useState(0);
  const [activePathway, setActivePathway] = useState(0);
  const [scrolled, setScrolled] = useState(false);
  const [journeyActive, setJourneyActive] = useState(0);
  const [activeAgent, setActiveAgent] = useState<string | null>(null);
  const [carouselStart, setCarouselStart] = useState<number | null>(null);
  const [projectFilter, setProjectFilter] = useState<(typeof projectFilters)[number]>("ALL");
  const [selectedProject, setSelectedProject] = useState<(typeof STUDENT_PROJECTS)[number] | null>(null);
  const [successStory, setSuccessStory] = useState(0);
  const [outputIndex, setOutputIndex] = useState(0);
  const [dividerPosition, setDividerPosition] = useState(50);
  const [mentorFilter, setMentorFilter] = useState<(typeof mentorFilters)[number]>("ALL");
  const [dashboardTilt, setDashboardTilt] = useState("0deg");

  const visibleProjects = STUDENT_PROJECTS.filter((project) => projectFilter === "ALL" || projectDomain(project.domain) === projectFilter);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 16);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  useEffect(() => {
    const updateJourney = () => {
      const journeySection = document.getElementById("platform");
      if (!journeySection) return;
      const progress = Math.min(1, Math.max(0, (window.scrollY - journeySection.offsetTop + window.innerHeight * 0.55) / (journeySection.offsetHeight * 0.72)));
      setJourneyActive(Math.min(journey.length - 1, Math.floor(progress * journey.length)));
    };
    updateJourney();
    window.addEventListener("scroll", updateJourney, { passive: true });
    return () => window.removeEventListener("scroll", updateJourney);
  }, []);

  const handleCarouselPointerDown = (event: React.PointerEvent<HTMLDivElement>) => setCarouselStart(event.clientX);
  const handleCarouselPointerUp = (event: React.PointerEvent<HTMLDivElement>) => {
    if (carouselStart === null) return;
    const distance = event.clientX - carouselStart;
    if (Math.abs(distance) > 35) setActivePathway((current) => Math.max(0, Math.min(pathways.length - 1, current + (distance < 0 ? 1 : -1))));
    setCarouselStart(null);
  };

  const updateDivider = (event: React.PointerEvent<HTMLDivElement>) => {
    const bounds = event.currentTarget.getBoundingClientRect();
    setDividerPosition(Math.min(94, Math.max(6, ((event.clientX - bounds.left) / bounds.width) * 100)));
  };

  return <main className="landing-page">
    <section className="landing-hero" style={{ backgroundImage: `url(${images.hero})` }}><div className="hero-shade" /><header className={scrolled ? "landing-nav is-scrolled" : "landing-nav"}><Link className="landing-logo" href="/">AAI–DBITIC</Link><nav className={menuOpen ? "landing-links is-open" : "landing-links"}><a href="#platform" onClick={() => setMenuOpen(false)}>Platform</a><a href="#agents" onClick={() => setMenuOpen(false)}>AI Agents</a><a href="#incubators" onClick={() => setMenuOpen(false)}>Incubation</a><a href="#impact" onClick={() => setMenuOpen(false)}>Projects</a><a href="#resources" onClick={() => setMenuOpen(false)}>Impact</a><a href="#resources" onClick={() => setMenuOpen(false)}>Events</a></nav><div className="nav-actions"><Link className="login-link" href="/login">Login</Link><Link className="pill-button light-pill" href="/signup">GET STARTED <ArrowRight size={15} /></Link></div><button className="menu-button" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></header><div className="hero-copy"><p className="eyebrow">AI-POWERED INNOVATION ECOSYSTEM</p><h1>BUILD YOUR<br /><span>NEXT BIG IDEA</span><br />INTO A REAL<br /><span className="venture-line">VENTURE.</span></h1><p className="hero-description">Connect research, branding, mentors, funding and startup support in one place so student ideas move from concept to traction faster.</p><div className="hero-buttons"><Link className="pill-button light-pill" href="/signup">START BUILDING <ArrowRight size={15} /></Link><Link className="video-button" href="#platform"><span className="play-icon"><ArrowRight size={12} /></span> EXPLORE PLATFORM <ArrowDownRight size={16} /></Link></div></div><div className="hero-3d-scene" aria-label="Incubation pipeline"><div className="hero-3d-plane plane-back"><span>03</span><strong>FUND</strong><small>Investor runway</small></div><div className="hero-3d-plane plane-mid"><span>02</span><strong>VALIDATE</strong><small>Proof &amp; traction</small></div><div className="hero-3d-plane plane-front"><span>01</span><strong>IDEA</strong><small>From classroom to market</small></div></div><div className="hero-campus-tag"><span>FROM CLASSROOM</span><span>TO MARKET</span></div><div className="hero-bottom"><div className="hero-stats"><div><strong>2017</strong><span>E-CELL FOUNDED</span></div><div><strong>16+</strong><span>EVENTS</span></div><div><strong>8</strong><span>AREAS</span></div><div><strong>1</strong><span>STUDENT ECOSYSTEM</span></div></div><div className="scroll-cue"><span /><small>SCROLL</small></div></div></section>
    <section className="brand-strip"><div className="brand-item">DBIT</div><div className="brand-item">AICTE</div><div className="brand-item">Startup India</div><div className="brand-item">NITI Aayog</div><div className="brand-item">Venture Catalysts</div><div className="brand-item">Microsoft</div><div className="brand-item">I-Hub</div><div className="brand-item">TIE</div></section>
    <section className="trust-strip section-light"><div className="section-kicker">Trusted by incubation centres, universities and innovation ecosystems</div><div className="trust-row"><strong>Entrepreneurship</strong><span>×</span><strong>Management</strong><span>×</span><strong>Finance</strong><span>×</span><strong>Mentors</strong><span>×</span><strong>Investors</strong></div></section>
    <section className="ecosystem-section" id="ecosystem"><div className="ecosystem-heading"><div><div className="section-kicker">INNOVATION ECOSYSTEM</div><h2>ONE ECOSYSTEM.<br /><em>DIFFERENT STARTING POINTS.</em></h2></div><p>Whether you&apos;re a student, faculty member, mentor, investor or industry partner, AAI–DBITIC gives you the right tools, people and opportunities.</p></div><div className="pathways-carousel" onPointerDown={handleCarouselPointerDown} onPointerUp={handleCarouselPointerUp} onPointerCancel={() => setCarouselStart(null)}>{pathways.map(([category, description, action, Icon, role, image], cardIndex) => <article className={activePathway === cardIndex ? "pathway-card active" : "pathway-card"} key={category} onMouseEnter={() => setActivePathway(cardIndex)}><div className="pathway-image" style={{ backgroundImage: `linear-gradient(180deg, transparent 20%, rgba(4,18,45,.9) 100%), url(${image})` }}><span>0{cardIndex + 1}</span><Icon size={20} /></div><div className="pathway-card-copy"><span className="pathway-category">{category}</span><h3>{category.split(" /")[0]}</h3><p>{description}</p><Link className="pathway-arrow" href={`/ecosystem/${role}`} aria-label={action}><ArrowUpRight size={18} /></Link></div></article>)}</div></section>
    <section className="problem-section section-light"><div className="problem-lead"><div className="section-kicker">ABOUT E-CELL</div><h2>Ideas are<br /><em>bulletproof.</em><br />Build them.</h2></div><div className="problem-copy"><p>DBIT’s E-Cell creates a platform for aspiring entrepreneurs to discuss ideas, produce business plans, and connect with mentors, incubators, and investors.</p><div className="problem-list"><span><b>01</b> Talks and workshops</span><span><b>02</b> Competitions and challenges</span><span><b>03</b> Finance and management</span><span><b>04</b> Social entrepreneurship</span></div></div></section>
    <section id="platform" className="journey-section section-light"><div className="journey-heading"><div><div className="section-kicker">INCUBATION JOURNEY</div><h2>ONE PROJECT.<br />AN <em>ENTIRE</em> VENTURE.</h2></div><p>From a raw idea to a launch-ready company, every stage has a clear next move.</p></div><div className="journey-track"><div className="journey-progress" style={{ width: `${((journeyActive + 1) / journey.length) * 100}%` }} /><div className="journey-stages">{journey.map(([number, title, description, Icon], index) => <button className={index === journeyActive ? "journey-stage active" : index < journeyActive ? "journey-stage complete" : "journey-stage"} key={number} onClick={() => setJourneyActive(index)}><span className="stage-dot"><Icon size={17} /></span><span className="step-number">{number}</span><strong>{title}</strong><small>{description}</small></button>)}</div></div></section>
    <section className="multimodal-section dark-section"><div className="multimodal-copy"><div className="section-kicker">MULTIMODAL AI</div><h2>IT UNDERSTANDS<br />MORE THAN TEXT.</h2><p>Upload your project in any format. The platform understands the complete context of your innovation.</p></div><div className="multimodal-stage" onMouseMove={(event) => { const target = event.currentTarget; target.style.setProperty("--pointer-x", `${(event.clientX / window.innerWidth - .5) * 16}deg`); target.style.setProperty("--pointer-y", `${(event.clientY / window.innerHeight - .5) * -12}deg`); }} onMouseLeave={(event) => { event.currentTarget.style.setProperty("--pointer-x", "0deg"); event.currentTarget.style.setProperty("--pointer-y", "0deg"); }}><div className="project-core">YOUR<br /><span>PROJECT</span></div>{[...formats, [FileText, "TEXT"] as const].map(([Icon, label], index) => <div className={`format-tile format-orbit orbit-${index + 1}`} key={label}><Icon size={22} /><span>{label === "Research Papers" ? "RESEARCH PAPER" : label.toUpperCase()}</span></div>)}</div></section>
    <section id="agents" className="agents-section section-light"><div className="agents-intro"><div className="section-kicker">AGENTIC AI</div><h2>DON&apos;T JUST ASK AI.<br />LET AI <em>ACT.</em></h2><p>A team of specialized AI agents works together to evaluate, validate and build your idea into a real startup.</p></div><div className="agent-orbit"><div className={activeAgent ? "agent-core is-active" : "agent-core"}>AI<br /><span>AGENTS</span></div><div className="agent-lines" />{agents.map(([name, description, Icon, color]) => <article className={activeAgent === name ? "agent-card active" : "agent-card"} key={name} onMouseEnter={() => setActiveAgent(name)} onMouseLeave={() => setActiveAgent(null)}><span className={`agent-icon ${color}`}><Icon size={20} /></span><div><strong>{name.toUpperCase()}</strong><p>{description}</p><small>Explore capability <ArrowUpRight size={12} /></small></div></article>)}</div></section>
    <section className="leadership-section section-light" id="leadership"><div className="leadership-portrait"><div className="portrait-placeholder"><Users size={44} /><span>PORTRAIT<br />PENDING</span></div><span className="portrait-caption">AAI–DBITIC INCUBATION LEADERSHIP</span></div><div className="leadership-copy"><div className="section-kicker">LEADERSHIP</div><h2>LEADERSHIP<br /><em>THAT DRIVES INNOVATION.</em></h2><div className="leader-meta"><span>HEAD OF INCUBATION</span><strong>NAME PENDING</strong><span>DESIGNATION PENDING</span></div><p>Leadership biography pending verified institutional information. Replace this editable placeholder with the official profile, credentials, and incubation mandate.</p><blockquote>&quot;Official leadership quote pending verified approval.&quot;</blockquote><div className="leadership-actions"><button className="outline-dark-button" type="button">VIEW PROFILE <ArrowRight size={15} /></button><button className="icon-text-button" type="button"><ArrowUpRight size={16} /> LinkedIn</button></div></div></section>
    <section className="team-section section-light"><div className="team-heading"><div><div className="section-kicker">THE PEOPLE BEHIND THE PLATFORM</div><h2>OUR CORE TEAM</h2></div><p>Verified team profiles will be added here once institutional names, roles, and approved photographs are available.</p></div><div className="team-carousel">{["COORDINATOR", "FACULTY IN-CHARGE", "INDUSTRY RELATIONS", "STARTUP MENTOR"].map((role) => <article className="team-card" key={role}><div className="team-photo"><Users size={30} /><span>PHOTO<br />PENDING</span></div><span className="team-role">{role}</span><h3>NAME PENDING</h3><p>Official designation pending</p></article>)}</div></section>
    <section className="projects-section section-light" id="projects"><div className="projects-heading"><div><div className="section-kicker">FEATURED PROJECTS</div><h2>IDEAS WE&apos;RE<br /><em>BUILDING.</em></h2></div><p>Workspace preview data from the existing project contract. Replace these demo records with verified incubated projects before publication.</p></div><div className="project-filters">{projectFilters.map((filter) => <button className={projectFilter === filter ? "active" : ""} key={filter} type="button" onClick={() => setProjectFilter(filter)}>{filter}</button>)}</div><div className="project-carousel">{visibleProjects.map((project) => <button className="project-card" key={project.id} type="button" onClick={() => setSelectedProject(project)}><div className="project-image"><span>{project.domain}</span><div className="project-image-mark"><Lightbulb size={27} /></div></div><div className="project-card-copy"><span className="project-stage">{projectStage(project.maturity)}</span><h3>{project.name}</h3><p>{project.shortDescription}</p><div><span>{project.teamSize} team members</span><ArrowUpRight size={17} /></div></div></button>)}</div>{visibleProjects.length === 0 && <div className="project-empty">No verified projects are available for this category yet.</div>}</section>
    {selectedProject && <div className="project-modal-backdrop" role="presentation" onClick={() => setSelectedProject(null)}><article className="project-modal" role="dialog" aria-modal="true" aria-label={selectedProject.name} onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" aria-label="Close project details" onClick={() => setSelectedProject(null)}><X size={20} /></button><div className="section-kicker">PROJECT PREVIEW</div><h2>{selectedProject.name}</h2><p className="modal-description">{selectedProject.shortDescription}</p><div className="project-detail-grid"><div><span>DOMAIN</span><strong>{selectedProject.domain}</strong></div><div><span>TEAM</span><strong>{selectedProject.teamSize} members</strong></div><div><span>CURRENT STAGE</span><strong>{projectStage(selectedProject.maturity)}</strong></div>{selectedProject.facultyGuide && <div><span>FACULTY GUIDE</span><strong>{selectedProject.facultyGuide}</strong></div>}</div><p className="modal-note">Problem, solution, technology, mentors, funding, and outcome details will appear here when verified project records are connected.</p></article></div>}
    <section className="funding-section dark-section" id="funding"><div className="funding-heading"><div><div className="section-kicker">FUNDING & OPPORTUNITY</div><h2>TURNING INNOVATION<br /><em>INTO OPPORTUNITIES.</em></h2></div><p>Helping promising innovations move from concepts to investment-ready ventures.</p></div><div className="funding-metrics">{["TOTAL FUNDING RAISED", "FUNDED PROJECTS", "INVESTOR CONNECTIONS", "FUNDING PROGRAMS"].map((metric) => <div key={metric}><strong>DATA PENDING</strong><span>{metric}</span></div>)}</div><div className="funding-track">{fundingJourney.map(([label, Icon], index) => <div className="funding-stage" key={label}><div className="funding-icon"><Icon size={19} /></div><span>0{index + 1}</span><strong>{label}</strong>{index < fundingJourney.length - 1 && <ArrowRight className="funding-arrow" size={20} />}</div>)}</div><p className="funding-note">Funding figures and programme names will be published after institutional verification.</p></section>
    <section id="incubators" className="split-section incubator-section dark-section" style={{ backgroundImage: `url(${images.lab})` }}><div className="dark-overlay" /><div className="split-copy"><div className="section-kicker">FOR INCUBATION CENTRES</div><h2>One Place to Run<br />Your Incubator.</h2><p>Manage projects, track progress, connect with mentors, and scale innovation — all in one platform.</p><Link className="pill-button light-pill" href="/login">View Dashboard <ArrowRight size={15} /></Link></div></section>
    <section className="outputs-section section-light"><div className="outputs-heading"><div className="section-kicker">WHAT AI CAN PRODUCE</div><h2>From a blank page<br />to a <em>launch plan.</em></h2><p>Every conversation becomes a useful artifact your team can review, refine and share.</p></div><div className="outputs-grid">{outputs.map(([name, description, Icon]) => <div className="output-item" key={name}><Icon size={19} /><div><strong>{name}</strong><p>{description}</p></div><ArrowUpRight size={15} /></div>)}</div></section>
    <section id="impact" className="impact-section section-light"><div className="impact-copy"><div className="section-kicker">EVENTS & INITIATIVES</div><h2>Learn by<br />doing <em>together.</em></h2><p>From Make-a-thons and Startup Forums to finance, branding, and problem-solving workshops, DBIT’s E-Cell bridges engineering with entrepreneurship.</p><div className="impact-stats">{[["2017", "E-Cell formed"], ["16+", "Event reports"], ["8", "Core initiatives"], ["3", "Growth pathways"], ["1", "Student community"]].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div><div className="impact-image" style={{ backgroundImage: `url(${images.campus})` }}><span>Talks<br />Workshops<br />Competitions<br />Mentorship<br />Impact</span></div></section>
    <section className="story-section dark-section" style={{ backgroundImage: `url(${images.office})` }}><div className="dark-overlay" /><div className="story-copy"><div className="section-kicker">A PROJECT, REIMAGINED</div><h2>From a student<br />question to a<br /><em>startup thesis.</em></h2><p>See the transformation from raw project context to a clear opportunity, business model and story worth sharing.</p><div className="story-flow"><span>Student project</span><ArrowRight size={17} /><span>AI analysis</span><ArrowRight size={17} /><span>Startup concept</span></div></div></section>
    <section className="demo-section section-light"><div className="demo-heading"><div><div className="section-kicker">EVENTS & REPORTS</div><h2>Learn by<br />building <em>together.</em></h2></div><p>Explore the initiative formats that help DBIT students develop entrepreneurial, management, finance, and problem-solving skills.</p></div><div className="demo-stage"><div className="demo-orbit orbit-one" /><div className="demo-orbit orbit-two" /><div className="demo-card" style={{ backgroundImage: `linear-gradient(180deg, transparent 30%, rgba(3,7,6,.92) 100%), url(${demoProjects[activeProject][4]})` }}><span className="demo-badge">DBIT E-CELL</span><div className="demo-card-copy"><span>INITIATIVE 0{activeProject + 1}</span><h3>{demoProjects[activeProject][0]}</h3><p>{demoProjects[activeProject][1]}</p></div></div><div className="demo-result"><span className="section-kicker">PATHWAY</span><strong>{demoProjects[activeProject][2]}</strong><p>{demoProjects[activeProject][3]}</p><span className="result-line" /></div></div><div className="demo-controls">{demoProjects.map(([name], index) => <button className={activeProject === index ? "demo-tab active" : "demo-tab"} key={name} onClick={() => setActiveProject(index)}><span>0{index + 1}</span>{name}</button>)}</div></section>
    <section className="stories-section section-light" id="stories"><div className="stories-heading"><div><div className="section-kicker">SUCCESS STORIES</div><h2>BUILT HERE.<br /><em>BUILT TO SCALE.</em></h2></div><p>Verified founder outcomes are not yet available in the project records. These cards reserve the editorial space without inventing a success story.</p></div><div className="story-carousel"><button className="story-nav" type="button" aria-label="Previous story" onClick={() => setSuccessStory((successStory + successStories.length - 1) % successStories.length)}><ArrowRight size={18} className="rotate-left" /></button><article className="success-story-card"><div className="story-image"><span>{successStories[successStory][0]}</span><div className="story-image-mark"><Building2 size={34} /></div></div><div className="success-story-copy"><span className="project-stage">{successStories[successStory][0]}</span><h3>{successStories[successStory][1]}</h3><div className="story-flow-labels"><span>PROJECT</span><ArrowRight size={15} /><span>INCUBATION</span><ArrowRight size={15} /><span>MENTORSHIP</span><ArrowRight size={15} /><span>FUNDING</span><ArrowRight size={15} /><span>STARTUP</span><ArrowRight size={15} /><span>IMPACT</span></div><div className="story-fields"><span><b>FOUNDER / STUDENT</b>{successStories[successStory][2]}</span><span><b>ACHIEVEMENT</b>{successStories[successStory][3]}</span><span><b>CURRENT STATUS</b>VERIFICATION PENDING</span></div></div></article><button className="story-nav" type="button" aria-label="Next story" onClick={() => setSuccessStory((successStory + 1) % successStories.length)}><ArrowRight size={18} /></button></div></section>
    <section className="impact-metrics-section section-light" id="impact-metrics"><div className="impact-metrics-heading"><div><div className="section-kicker">IMPACT</div><h2>MEASURE WHAT<br /><em>MATTERS.</em></h2></div><p>Verified institutional metrics will animate here when connected. No statistics are presented from the current UI-only mock data.</p></div><div className="impact-metrics-grid">{impactMetrics.map((metric) => <div className="impact-metric" key={metric}><strong>--</strong><span>{metric}</span><small>DATA PENDING</small></div>)}</div><div className="milestones-row">{["AWARDS", "COMPETITIONS", "GRANTS", "RECOGNITIONS", "PARTNERSHIPS", "MILESTONES"].map((item) => <span key={item}>{item}<b>VERIFICATION PENDING</b></span>)}</div></section>
    <section className="dashboard-section section-light" id="dashboard"><div className="dashboard-heading"><div><div className="section-kicker">INCUBATOR DASHBOARD</div><h2>A POWERFUL DASHBOARD<br /><em>FOR INCUBATION CENTRES.</em></h2></div><p>Product preview only. Connect verified operational data before using this surface for reporting or decision-making.</p></div><div className="dashboard-frame" onMouseMove={(event) => { const bounds = event.currentTarget.getBoundingClientRect(); setDashboardTilt(`${((event.clientX - bounds.left) / bounds.width - .5) * 5}deg`); }} onMouseLeave={() => setDashboardTilt("0deg")} style={{ transform: `perspective(1400px) rotateY(${dashboardTilt})` }}><aside className="dashboard-sidebar"><strong>AAI–DBITIC</strong><span className="dashboard-sidebar-active">Overview</span><span>Projects & Startups</span><span>Mentors & Experts</span><span>Programs & Events</span><span>Analytics & Reports</span><span>Funding & Grants</span></aside><div className="dashboard-main"><div className="dashboard-topbar"><span>Incubator overview</span><span className="dashboard-status">PRODUCT PREVIEW</span></div><div className="dashboard-kpis"><div><span>ACTIVE PROJECTS</span><strong>--</strong></div><div><span>IN REVIEW</span><strong>--</strong></div><div><span>MENTOR SESSIONS</span><strong>--</strong></div><div><span>FUNDING PIPELINE</span><strong>--</strong></div></div><div className="dashboard-columns"><div className="dashboard-panel"><div className="panel-heading"><strong>Project pipeline</strong><span>View all</span></div><div className="pipeline-row"><span>IDEATION</span><i /><i /><i /></div><div className="pipeline-row"><span>PROTOTYPE</span><i /><i /></div><div className="pipeline-row"><span>MARKET READY</span><i /></div></div><div className="dashboard-panel chart-panel"><div className="panel-heading"><strong>Progress overview</strong><span>12 weeks</span></div><div className="chart-bars"><i /><i /><i /><i /><i /><i /><i /><i /></div></div></div><div className="dashboard-table"><div className="panel-heading"><strong>Recent activity</strong><span>Updated moments ago</span></div><div><span>Project evaluation</span><b>Pending data</b></div><div><span>Mentor matching</span><b>Pending data</b></div><div><span>Grant application</span><b>Pending data</b></div></div></div></div></section>
    <section className="outputs-carousel-section section-light" id="ai-outputs"><div className="outputs-carousel-heading"><div><div className="section-kicker">AI OUTPUTS</div><h2>FROM A BLANK PAGE<br /><em>TO A LAUNCH PLAN.</em></h2></div><p>Move through the product artifacts your team can review, refine, and share.</p></div><div className="outputs-carousel"><button className="output-nav" type="button" aria-label="Previous output" onClick={() => setOutputIndex((outputIndex + outputs.length - 1) % outputs.length)}><ArrowRight size={18} className="rotate-left" /></button><article className="document-preview"><div className="document-top"><span>AAI–DBITIC / AI WORKSPACE</span><span>0{outputIndex + 1}</span></div><div className="document-lines"><span /><span /><span /><span /><span /><span /></div><div className="document-title"><strong>{outputs[outputIndex][0].toUpperCase()}</strong><small>{outputs[outputIndex][1]}</small></div><div className="document-stamp">REVIEW<br />READY</div></article><div className="output-list">{outputs.map(([name], index) => <button className={outputIndex === index ? "active" : ""} key={name} type="button" onClick={() => setOutputIndex(index)}><span>0{index + 1}</span>{name}<ArrowUpRight size={15} /></button>)}</div><button className="output-nav" type="button" aria-label="Next output" onClick={() => setOutputIndex((outputIndex + 1) % outputs.length)}><ArrowRight size={18} /></button></div></section>
    <section className="compare-section dark-section" id="from-classroom"><div className="compare-heading"><div><div className="section-kicker">PROJECT TO STARTUP</div><h2>FROM CLASSROOM<br /><em>TO MARKET.</em></h2></div><p>Comparison preview only. The right side becomes a real startup artifact when verified project inputs are available.</p></div><div className="compare-slider" onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); updateDivider(event); }} onPointerMove={(event) => { if (event.currentTarget.hasPointerCapture(event.pointerId)) updateDivider(event); }} style={{ "--divider": `${dividerPosition}%` } as React.CSSProperties}><div className="compare-pane compare-startup"><span className="compare-label">STARTUP READY</span><h3>VERIFIED DATA<br />PENDING</h3><div><span>Startup Name</span><span>Market Analysis</span><span>Business Model</span><span>Pitch Deck</span><span>Mentor Recommendation</span></div></div><div className="compare-pane compare-project"><span className="compare-label">STUDENT PROJECT</span><h3>PROJECT INPUTS<br />PENDING</h3><div><span>Report</span><span>Prototype</span><span>Notes</span><span>GitHub</span><span>Screenshots</span></div></div><div className="compare-divider"><span><ArrowRight size={14} /><ArrowRight size={14} /></span></div></div></section>
    <section className="events-section dark-section" id="events"><div className="events-heading"><div><div className="section-kicker">EVENTS & INITIATIVES</div><h2>LEARN BY<br /><em>DOING TOGETHER.</em></h2></div><p>Official event records are not available in the current project data. These clearly labelled placeholders reserve the programme story.</p></div><div className="events-carousel">{eventTypes.map((eventType, index) => <article className="event-card" key={eventType}><div className="event-image"><span>DEMO EVENT</span><strong>0{index + 1}</strong></div><div className="event-card-copy"><span>DATE PENDING · {eventType}</span><h3>{eventType}</h3><p>Official description and event photography will be added after verification.</p><ArrowUpRight size={18} /></div></article>)}</div></section>
    <section className="mentors-section section-light" id="mentors"><div className="mentors-heading"><div><div className="section-kicker">MENTOR NETWORK</div><h2>THE RIGHT PEOPLE<br /><em>CAN CHANGE THE TRAJECTORY.</em></h2></div><p>Verified mentor profiles will be published here once names, designations, expertise, and approved portraits are available.</p></div><div className="mentor-filters">{mentorFilters.map((filter) => <button className={mentorFilter === filter ? "active" : ""} key={filter} type="button" onClick={() => setMentorFilter(filter)}>{filter}</button>)}</div><div className="mentor-cards">{["MENTOR PROFILE 01", "MENTOR PROFILE 02", "MENTOR PROFILE 03", "MENTOR PROFILE 04"].map((profile) => <article className="mentor-card" key={profile}><div className="mentor-photo"><Users size={30} /><span>PHOTO<br />PENDING</span></div><span className="mentor-filter-label">{mentorFilter === "ALL" ? "EXPERTISE PENDING" : mentorFilter}</span><h3>NAME PENDING</h3><p>Designation pending · Industry pending</p><small>Mentoring area pending</small></article>)}</div></section>
    <section className="network-section section-light" id="network"><div className="network-heading"><div><div className="section-kicker">ECOSYSTEM CONNECTION</div><h2>CONNECTED TO<br /><em>THE REAL WORLD.</em></h2></div><p>AAI–DBITIC connects university energy to the people and pathways that help ideas move beyond campus.</p></div><div className="network-flow">{["UNIVERSITY", "INCUBATION", "INDUSTRY", "MENTORS", "INVESTORS", "STARTUPS", "IMPACT"].map((label, index) => <div className="network-node" key={label}><span>{String(index + 1).padStart(2, "0")}</span><strong>{label}</strong>{index < 6 && <ArrowDownRight className="network-arrow" size={18} />}</div>)}</div></section>
    <section id="resources" className="closing-section dark-section final-cta" style={{ backgroundImage: `url(${images.hero})` }}><div className="dark-overlay" /><div className="closing-copy"><div className="section-kicker">THE OPPORTUNITY</div><h2>THE NEXT STARTUP<br />IS ALREADY HERE.</h2><p>Help discover it. Build it. Validate it. Fund it. Launch it.</p><div className="hero-buttons"><Link className="pill-button light-pill" href="/signup">GET STARTED <ArrowRight size={15} /></Link><a className="footer-link" href="mailto:hello@aai-dbitic.example">TALK TO OUR TEAM <ArrowRight size={15} /></a></div></div></section>
    <footer className="landing-footer final-footer"><div className="footer-brand"><Link className="footer-logo" href="/">AAI–DBITIC</Link><p>AI-powered innovation and incubation for ideas ready to move.</p></div><div className="footer-column"><strong>PLATFORM</strong><a href="#platform">Overview</a><a href="#agents">AI Agents</a><a href="#dashboard">Dashboard</a></div><div className="footer-column"><strong>INCUBATION</strong><a href="#leadership">Leadership</a><a href="#projects">Projects</a><a href="#mentors">Mentors</a><a href="#funding">Funding</a><a href="#stories">Success Stories</a></div><div className="footer-column"><strong>ECOSYSTEM</strong><a href="#ecosystem">E-Cell</a><a href="#events">Events</a><a href="#ecosystem">Partners</a><a href="#stories">Startups</a></div><div className="footer-column"><strong>RESOURCES</strong><a href="#ai-outputs">Documentation</a><a href="#stories">Case Studies</a><a href="#resources">Blog</a></div><div className="footer-column"><strong>COMPANY</strong><a href="#leadership">About</a><a href="mailto:hello@aai-dbitic.example">Contact</a></div><div className="footer-legal"><span>Privacy Policy</span><span>Terms of Use</span><span className="footer-socials"><a href="mailto:hello@aai-dbitic.example" aria-label="LinkedIn">in</a><a href="mailto:hello@aai-dbitic.example" aria-label="Instagram">◎</a><a href="mailto:hello@aai-dbitic.example" aria-label="YouTube">▶</a></span></div></footer>
  </main>;
}
